on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{AKIASAQQT4IWT76KB4NZ}}
          aws-secret-access-key: ${{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}}
          aws-region: ##us-east-1##
      # sam build
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket ##erpsuites-github-test## --capabilities CAPABILITY_IAM --region ##us-east-1##